// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hUpVgN8iDUq0YvpJD0AM_AGrSQxQMhk',
    appId: '1:701640467396:web:72152221727213187d3a91',
    messagingSenderId: '701640467396',
    projectId: 'crave-mate-admin',
    authDomain: 'crave-mate-admin.firebaseapp.com',
    storageBucket: 'crave-mate-admin.firebasestorage.app',
    measurementId: 'G-D8M6BMXRRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopuESuIaax0KTUrrh3J_CTVEcwoRvblE',
    appId: '1:701640467396:android:0e70f9a7870c3f7b7d3a91',
    messagingSenderId: '701640467396',
    projectId: 'crave-mate-admin',
    storageBucket: 'crave-mate-admin.firebasestorage.app',
  );
}
